### ISSUE TITLE
un-handled errors - shard doesn't exist

### ISSUE THREAD

**Issue by sgreifan** [ironSource/node-dynamodb-stream#8] opened 2017-02-02 07:05 UTC
This might might be 2 different issues, but it seems connected:

After a long period of time (about 2 days usually) while the `ddbStream.fetchStreamState` method is called every 30 seconds.
An error is returned in the callback: "shard doesn't exist"
After that happens, this error is returned on each callback and the db is no longer updated.

Before that happens, sometimes there is a parse error returned: `Unexpected token <`
But this doesn't seem to break the logic, the app keeps running and updating.

**Comment by jeka-kiselyov** [comment] 2017-04-07 19:38
@sgreifan did you have a chance to figure this out? I have the same issue here. Sometimes it stops getting events after "[MissingRequiredParameter: Missing required key 'ShardIterator' in params]" error in fetchStreamState.

**Comment by sgreifan** [comment] 2017-04-12 08:00
@jeka-kiselyov not yet, added a walk around for now.
I'll update when i'll get to it, please update if you do before me

**Comment by jeka-kiselyov** [comment] 2017-04-12 08:13
I'm not sure, but looks that the issue was because fetchStreamState has been called before callback from previous call(when there're delays in network or interval is too short) . This is how I reproduce it. But it was rare, so I don't know if I've fixed it assuring there're no parallel calls, or just lucky for now.

**Comment by ChristopheBougere** [comment] 2017-06-04 16:34
I have the same issue `MissingRequiredParameter: Missing required key 'ShardIterator' in params` and it always happens after at least one day running
@jeka-kiselyov could you provide the patch you applied to fix the callback issue?
This repo does not seems to be still updated, but we can still try a PR...

**Comment by jeka-kiselyov** [comment] 2017-06-04 18:14
@ChristopheBougere There're no changes in library itself. And I think it's AWS bug, to be honest. But can't prove as it's still very hard to catch that bug. Code like this works ok (~2.5 weeks constant running now):
`
var ddbStream = null;
var startStream = function() {
  ddbStream = new DynamoDBStream(dynamodbstreams, config.dynamoDBSteamARN);
  ddbStream.fetchStreamState(fetchstateCallback);
}
var fetchstateCallback = function(err) {
    if (err) {
      setTimeout(function(){
        startStream();
      }, config.dynamoDBChat.dynamoDBSteamRestartInterval); /// 5000 in my case
    } else {
      setTimeout(function(){
        ddbStream.fetchStreamState(fetchstateCallback);
      }, config.dynamoDBChat.dynamoDBSteamCheckInterval);  /// 1000 in my case
    }
};
startStream();
`

It's not elegant, but does restart DynamoDBStream if there's error(which fix proccess, though it may take few restarts). Also, be sure to put it to single instance or singleton, to be sure there's only one active 'DynamoDBStream' instance per dynamoDBSteamARN and one fetchStreamState call in progress.

**Comment by ChristopheBougere** [comment] 2017-06-04 18:41
@jeka-kiselyov Ah ok thanks!
That "catch & restart stream" was my last try, and I have the same issue but I'll have a second look on how I implemented it (maybe it wasn't closed properly).
AWS recommand to use Kinesis Adapter to consume DDB streams (cf. http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.KCLAdapter.html).
I'm considering to use it but it complicates a lot the implementation (even more in JS) compared to the use of this package :/

**Comment by jeka-kiselyov** [comment] 2017-06-04 19:46
@ChristopheBougere yep, in my project I don't need 100% events, it's ok if I miss few 'insert record' events, so I was like ok with this quick dirty fix. I've spent an hour or two checking Kinesis and trying to find nice lib that covers it and dynamodb and had no luck. Was even thinking about building some Lambda middleware(may be nice idea), but don't want to spend too much time for such simple task(it's just getting new records from db, it should be easier).

**Comment by kessler** [comment] 2021-02-01 07:18
@ChristopheBougere @jeka-kiselyov i know it's been a while but I did a revamp on this codebase + trying to close / fix all issues, can you maybe comment on this somehow?

**Comment by ChristopheBougere** [comment] 2021-02-01 08:07
Sorry couldn't tell you, I'm not using it anymore on my current projects

**Comment by jeka-kiselyov** [comment] 2021-02-01 10:09
I am same as Christophe. @kessler but I beleive you can close this one. 99% that this was AWS bug, and as there're no more comments here, 99% that it's fixed by them.

**Comment by kessler** [comment] 2021-02-01 13:08
alright guys, thanks!

**Closed by kessler** 2021-02-01 13:08 UTC
